/* Service worker + auto-update checks. The SW is generated by build.py, so these
   assert the shipped sw.js and the registration block in index.html actually
   implement the update strategy. */
const fs=require('fs');
const sw=fs.readFileSync('sw.js','utf8');
const html=fs.readFileSync('index.html','utf8');
let pass=0,fail=0;
function t(n,ok){ok?(pass++,console.log('  ok   '+n)):(fail++,console.log('  FAIL '+n));}

// sw.js is valid JS
try{ new Function('self','caches','fetch','location',sw); t('sw.js parses',true); }
catch(e){ t('sw.js parses',false); }

// HTML must be network-first, or an installed app can never see a new build
const htmlBranch=sw.slice(sw.indexOf('if(isHTML'), sw.indexOf('// Everything else'));
t('HTML branch exists', htmlBranch.length>0);
t('HTML is network-first', htmlBranch.indexOf('fetch(req)')>=0 && htmlBranch.indexOf('fetch(req)')<htmlBranch.indexOf('caches.match'));
t('HTML falls back to cache offline', htmlBranch.includes('caches.match("./index.html")'));

// assets stay cache-first so offline use is unaffected
const assetBranch=sw.slice(sw.indexOf('// Everything else'));
t('assets are cache-first', assetBranch.indexOf('caches.match(req)')<assetBranch.indexOf('fetch(req)'));

// lifecycle
t('install skips waiting', sw.includes('self.skipWaiting()'));
t('activate purges old caches', sw.includes('k!==CACHE') && sw.includes('caches.delete'));
t('activate claims clients', sw.includes('clients.claim'));
t('accepts SKIP_WAITING message', sw.includes('"SKIP_WAITING"') || sw.includes("'SKIP_WAITING'"));

// cache name must match APP_VERSION, or an update ships without busting the cache
const cacheV=(sw.match(/coffee-guide-(v\d+)/)||[])[1];
const appV=(html.match(/"APP_VERSION":\s*"(v\d+)"/)||[])[1];
t('cache version matches APP_VERSION ('+cacheV+' / '+appV+')', !!cacheV && cacheV===appV);

// registration side
t('registers with updateViaCache none', html.includes("updateViaCache:'none'"));
t('listens for controllerchange', html.includes('controllerchange'));
t('reloads once on controllerchange', html.includes('reloading') && html.includes('location.reload()'));
t('activates waiting worker', html.includes("postMessage('SKIP_WAITING')"));
t('checks for updates on refocus', html.includes('visibilitychange') && html.includes('reg.update()'));
t('polls periodically', html.includes('setInterval(check'));

console.log('');
console.log(pass+' passed, '+fail+' failed');
process.exit(fail?1:0);
